---
- hosts: prod
  become: yes
  vars_files:
    - files/secrets/credentials.yml
  roles: 
    - role: '/home/vagrant/mario/roles/mario/tasks/main.yml'


#  vars:
#     system_user: vagrant
#  vars_files:
#     - files/secrets/credentials.yml
